Update ecs_generic_deploy.yml

diff --git a/.github/workflows/ecs_generic_deploy.yml b/.github/workflows/ecs_generic_deploy.yml
--- a/.github/workflows/ecs_generic_deploy.yml
+++ b/.github/workflows/ecs_generic_deploy.yml
@@ -109,6 +109,36 @@ jobs:
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install
+          
+      - name: Check if Image Exists
+        env:
+          AWS_REGION: ${{ steps.set_region.outputs.region }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          IMAGE_NAME=${{ steps.image-name.outputs.image }}
+          TAG_NAME=$(echo $IMAGE_NAME | awk -F: '{print $2}')
+          
+          end=$((SECONDS+900))  # 15 minutes = 900 seconds
+          while [ $SECONDS -lt $end ]; do
+            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
+            echo "$TIMESTAMP: Checking for image with tag $TAG_NAME in repository..."
+            
+            # Use AWS CLI to check if image with the tag exists
+            IMAGES=$(aws ecr list-images --repository-name ${{inputs.ecr_repo}} --region $AWS_REGION)
+            
+            if echo "$IMAGES" | grep -q "$TAG_NAME"; then
+              echo "$TIMESTAMP: Image with tag $TAG_NAME found!"
+              exit 0
+            fi
+            
+            # Wait for 30 seconds before next check
+            sleep 30
+          done
+      
+          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
+          echo "$TIMESTAMP: Image with tag $TAG_NAME not found after 15 minutes. Exiting..."
+          exit 1
 
       - name: Grab Live Task_Definition
         env:
